class BlockChainGenerator:
    def __init__(self, difficulty: int) -> None: ...
    def add_block(self, filename: str, original_loc: str, data: bytes, encrypted: bool) -> None: ...
    def len(self) -> int: ...
    def iterate_and_write(self, filename_or_index: str, loc: str) -> str: ...
    def valid(self) -> bool: ...
    def load_backup(self, loc: str) -> None: ...
    def exit_protocol(self, loc: str) -> None: ...
    def list(self) -> list[str]: ...
    def iterate_and_find(self, filename: str) -> bytes: ...