name: Build

on: push

jobs:
    Build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Build Test
              uses: d33p0st/python-rust-mix-build@v4
              with:
                python-version: 3.12
            
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.12
            
            - name: Build Test 2
              run: |
                python -m pip install --upgrade pip
                pip install .